# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jgp8F40dlf7qxN3rRVsY4yVJkueFn_US
"""

pip install google-play-scraper

from google_play_scraper import reviews, Sort
import csv
import pandas as pd
from transformers import pipeline

# Existing code to scrape and save reviews
result, _ = reviews(
    'net.sinergics.abon.swinmandiri',
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=100,
    filter_score_with=None
)

filename = 'ulasan_google_play.csv'


with open(filename, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=['userName', 'score', 'at', 'content'])
    writer.writeheader()
    for review_item in result:

        writer.writerow({
            'userName': review_item['userName'],
            'score': review_item['score'],
            'at': review_item['at'],
            'content': review_item['content']
        })

print(f"Berhasil menyimpan {len(result)} ulasan ke '{filename}'")

# Load the CSV file into a Pandas DataFrame
df = pd.read_csv(filename)

# Initialize the sentiment analysis pipeline with Indo-Roberta
print("Loading Indo-Roberta sentiment analysis model...")
sentiment_pipeline = pipeline("sentiment-analysis", model="w11wo/indonesian-roberta-base-sentiment-classifier")
print("Model loaded successfully.")

# Function to get sentiment from text
def get_sentiment(text):
    if pd.isna(text) or text.strip() == "":
        return {"label": "NEUTRAL", "score": 0.0} # Handle empty or NaN content
    try:
        return sentiment_pipeline(text)[0]
    except Exception as e:
        print(f"Error processing text: {text}. Error: {e}")
        return {"label": "ERROR", "score": 0.0}

# Apply sentiment analysis to the 'content' column
df['sentiment_result'] = df['content'].apply(get_sentiment)

# Extract label and score into separate columns
df['sentiment_label'] = df['sentiment_result'].apply(lambda x: x['label'])
df['sentiment_score'] = df['sentiment_result'].apply(lambda x: x['score'])

# Drop the intermediate sentiment_result column if desired
df = df.drop(columns=['sentiment_result'])

# Display the first few rows with sentiment analysis results
print("\nSentiment Analysis Results:")
print(df[['content', 'sentiment_label', 'sentiment_score']].head())

# Display sentiment distribution
print("\nSentiment Distribution:")
print(df['sentiment_label'].value_counts())

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate sentiment distribution
sentiment_counts = df['sentiment_label'].value_counts()

# Create a bar plot for sentiment distribution
plt.figure(figsize=(8, 6))
sns.barplot(x=sentiment_counts.index, y=sentiment_counts.values, hue=sentiment_counts.index, palette='viridis', legend=False)
plt.title('Sentiment Distribution of Google Play Reviews')
plt.xlabel('Sentiment Label')
plt.ylabel('Number of Reviews')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()